package:
  name: snowmicropyn
  version: 0.0.22

source:
  git_rev: v0.0.22
  git_url: https://github.com/marrcl/smp.git

requirements:
  build:
    - python
  run:
    - python
    - scipy ==0.17
    - matplotlib ==1.5
    - wxpython ==3

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  osx_is_app: True

test:
  imports:

about:
  home: https://www.slf.ch
  license: GPL
