package:
  name: snowmicropyn
  version: 0.0.22

source:
  git_rev: v0.0.22
  git_url: https://github.com/marrcl/smp.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib ==1.5.*
    - wxpython ==3.*
    - scipy ==0.13.*

build:
  script: python setup.py install

test:
  imports:

about:
  home: https://www.slf.ch
  license: GPL
