package:
  name: snowmicropyn
  version: 0.0.20

source:
  path: ..

requirements:
  build:
    - python
    - scipy ==0.17
    - matplotlib ==1.5
    - wxpython ==3
  run:
    - python
    - scipy ==0.17
    - matplotlib ==1.5
    - wxpython ==3

build:
  noarch: python
  script: python setup.py install

about:
  home: https://www.slf.ch
  license: GPL
  summary: Analyzing tool for snow profiles recorded by SnowMicroPen, a penetration probe for snow for scientific purposes.

